### ISSUE TITLE
Unable to build C++ wave_api_stream example 

### ISSUE THREAD

**Issue by antiero** [genkiinstruments/genki-wave#54]
Hello, I'm trying to build the C++ wave_api_stream example (my end goal is to build a Unity Plugin, but this was my first step!)

I have run through the build instructions which completed without errors:

```
cmake -B build_dir
cmake --build build_dir

```

Then cd into `cpp/examples/wave_api_stream`, and do what I assume I should do with cmake:

```
mkdir build 
cd build 
cmake ..
```

But I get build errors:

```
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (juce_add_console_app):
  Unknown CMake command "juce_add_console_app".
```

Can someone advise please? (also if anyone has done any C#/Unity integration already with Genki Wave that would be great headstart for me! :) )

**Comment by dingari** [comment]
I'm going to go ahead and close this issue. If you're still having troubles, feel free to open another one :)
